-- ─────────────────────────────────────────────────────────────────────────────
-- 0016 — SEED RBAC catalog (roles/permissions/grants) + tenant Trường Việt Anh.
-- SINH TỰ ĐỘNG bởi scripts/gen-rbac-migration.mjs từ packages/db/src/seed-rbac.ts
-- (nguồn chân lý). Đưa catalog RBAC vào migration tracked cho nhà mới. Idempotent.
-- KHÔNG seed người dùng thật ở đây (SSO/roster lo); acc demo do seed:demo.
-- ─────────────────────────────────────────────────────────────────────────────

-- Tenant (một trường)
insert into public.tenants (name, slug) values ('Trường Việt Anh', 'viet-anh')
  on conflict (slug) do nothing;

-- Roles
insert into public.roles (key, label) values ('student', 'Học sinh') on conflict (key) do update set label = excluded.label;
insert into public.roles (key, label) values ('parent', 'Phụ huynh') on conflict (key) do update set label = excluded.label;
insert into public.roles (key, label) values ('teacher', 'Giáo viên bộ môn') on conflict (key) do update set label = excluded.label;
insert into public.roles (key, label) values ('homeroom_teacher', 'Giáo viên chủ nhiệm') on conflict (key) do update set label = excluded.label;
insert into public.roles (key, label) values ('subject_lead', 'Tổ trưởng chuyên môn') on conflict (key) do update set label = excluded.label;
insert into public.roles (key, label) values ('counselor', 'Cố vấn tâm lý') on conflict (key) do update set label = excluded.label;
insert into public.roles (key, label) values ('content_author', 'Đội nội dung — soạn') on conflict (key) do update set label = excluded.label;
insert into public.roles (key, label) values ('content_reviewer', 'Đội nội dung — duyệt') on conflict (key) do update set label = excluded.label;
insert into public.roles (key, label) values ('campus_admin', 'Quản lý cơ sở') on conflict (key) do update set label = excluded.label;
insert into public.roles (key, label) values ('leadership', 'Ban giám hiệu') on conflict (key) do update set label = excluded.label;
insert into public.roles (key, label) values ('dpo', 'Cán bộ bảo vệ dữ liệu') on conflict (key) do update set label = excluded.label;
insert into public.roles (key, label) values ('admin', 'Admin hệ thống') on conflict (key) do update set label = excluded.label;

-- Permissions
insert into public.permissions (key, domain) values ('org:tenant:read', 'org') on conflict (key) do update set domain = excluded.domain;
insert into public.permissions (key, domain) values ('org:tenant:configure', 'org') on conflict (key) do update set domain = excluded.domain;
insert into public.permissions (key, domain) values ('org:campus:manage', 'org') on conflict (key) do update set domain = excluded.domain;
insert into public.permissions (key, domain) values ('org:class:manage', 'org') on conflict (key) do update set domain = excluded.domain;
insert into public.permissions (key, domain) values ('iam:user:manage', 'iam') on conflict (key) do update set domain = excluded.domain;
insert into public.permissions (key, domain) values ('iam:role:grant', 'iam') on conflict (key) do update set domain = excluded.domain;
insert into public.permissions (key, domain) values ('iam:permission:simulate', 'iam') on conflict (key) do update set domain = excluded.domain;
insert into public.permissions (key, domain) values ('privacy:consent:read', 'privacy') on conflict (key) do update set domain = excluded.domain;
insert into public.permissions (key, domain) values ('privacy:consent:grant', 'privacy') on conflict (key) do update set domain = excluded.domain;
insert into public.permissions (key, domain) values ('privacy:consent:withdraw', 'privacy') on conflict (key) do update set domain = excluded.domain;
insert into public.permissions (key, domain) values ('privacy:dsar:fulfill', 'privacy') on conflict (key) do update set domain = excluded.domain;
insert into public.permissions (key, domain) values ('privacy:dpia:manage', 'privacy') on conflict (key) do update set domain = excluded.domain;
insert into public.permissions (key, domain) values ('content:kg:read', 'content') on conflict (key) do update set domain = excluded.domain;
insert into public.permissions (key, domain) values ('content:node:write', 'content') on conflict (key) do update set domain = excluded.domain;
insert into public.permissions (key, domain) values ('content:question:read', 'content') on conflict (key) do update set domain = excluded.domain;
insert into public.permissions (key, domain) values ('content:question:write', 'content') on conflict (key) do update set domain = excluded.domain;
insert into public.permissions (key, domain) values ('content:ladder:write', 'content') on conflict (key) do update set domain = excluded.domain;
insert into public.permissions (key, domain) values ('content:review:approve', 'content') on conflict (key) do update set domain = excluded.domain;
insert into public.permissions (key, domain) values ('content:question:retire', 'content') on conflict (key) do update set domain = excluded.domain;
insert into public.permissions (key, domain) values ('learn:tutor:chat', 'learn') on conflict (key) do update set domain = excluded.domain;
insert into public.permissions (key, domain) values ('learn:session:read_own', 'learn') on conflict (key) do update set domain = excluded.domain;
insert into public.permissions (key, domain) values ('learn:session:read_scope', 'learn') on conflict (key) do update set domain = excluded.domain;
insert into public.permissions (key, domain) values ('learn:mastery:read_own', 'learn') on conflict (key) do update set domain = excluded.domain;
insert into public.permissions (key, domain) values ('learn:mastery:read_scope', 'learn') on conflict (key) do update set domain = excluded.domain;
insert into public.permissions (key, domain) values ('learn:attempt:read_scope', 'learn') on conflict (key) do update set domain = excluded.domain;
insert into public.permissions (key, domain) values ('config:tenant:update', 'config') on conflict (key) do update set domain = excluded.domain;
insert into public.permissions (key, domain) values ('config:subject:update', 'config') on conflict (key) do update set domain = excluded.domain;
insert into public.permissions (key, domain) values ('config:class:update', 'config') on conflict (key) do update set domain = excluded.domain;
insert into public.permissions (key, domain) values ('config:student:update', 'config') on conflict (key) do update set domain = excluded.domain;
insert into public.permissions (key, domain) values ('config:feature_flag:update', 'config') on conflict (key) do update set domain = excluded.domain;
insert into public.permissions (key, domain) values ('assess:summative:grade', 'assess') on conflict (key) do update set domain = excluded.domain;
insert into public.permissions (key, domain) values ('intervene:manage', 'assess') on conflict (key) do update set domain = excluded.domain;
insert into public.permissions (key, domain) values ('live:classroom:run', 'assess') on conflict (key) do update set domain = excluded.domain;
insert into public.permissions (key, domain) values ('report:student:read', 'report') on conflict (key) do update set domain = excluded.domain;
insert into public.permissions (key, domain) values ('report:class:read', 'report') on conflict (key) do update set domain = excluded.domain;
insert into public.permissions (key, domain) values ('report:school:read', 'report') on conflict (key) do update set domain = excluded.domain;
insert into public.permissions (key, domain) values ('report:parent:read', 'report') on conflict (key) do update set domain = excluded.domain;
insert into public.permissions (key, domain) values ('safety:flag:read', 'safety') on conflict (key) do update set domain = excluded.domain;
insert into public.permissions (key, domain) values ('safety:flag:verify', 'safety') on conflict (key) do update set domain = excluded.domain;
insert into public.permissions (key, domain) values ('safety:flag:resolve', 'safety') on conflict (key) do update set domain = excluded.domain;
insert into public.permissions (key, domain) values ('wellbeing:context:read', 'safety') on conflict (key) do update set domain = excluded.domain;
insert into public.permissions (key, domain) values ('ai:prompt:manage', 'ai') on conflict (key) do update set domain = excluded.domain;
insert into public.permissions (key, domain) values ('ai:model:configure', 'ai') on conflict (key) do update set domain = excluded.domain;
insert into public.permissions (key, domain) values ('ai:budget:read', 'ai') on conflict (key) do update set domain = excluded.domain;
insert into public.permissions (key, domain) values ('ai:eval:run', 'ai') on conflict (key) do update set domain = excluded.domain;
insert into public.permissions (key, domain) values ('audit:log:read', 'audit') on conflict (key) do update set domain = excluded.domain;
insert into public.permissions (key, domain) values ('ops:manage', 'ops') on conflict (key) do update set domain = excluded.domain;
insert into public.permissions (key, domain) values ('saas:manage', 'saas') on conflict (key) do update set domain = excluded.domain;

-- Role → permission grants (xoá sạch rồi cấp lại để khớp nguồn)
delete from public.role_permissions where role_key = 'student';
insert into public.role_permissions (role_key, perm_key) values ('student', 'learn:tutor:chat') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('student', 'learn:session:read_own') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('student', 'learn:mastery:read_own') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('student', 'privacy:consent:read') on conflict do nothing;
delete from public.role_permissions where role_key = 'parent';
insert into public.role_permissions (role_key, perm_key) values ('parent', 'report:parent:read') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('parent', 'privacy:consent:read') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('parent', 'privacy:consent:grant') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('parent', 'privacy:consent:withdraw') on conflict do nothing;
delete from public.role_permissions where role_key = 'teacher';
insert into public.role_permissions (role_key, perm_key) values ('teacher', 'content:kg:read') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('teacher', 'content:question:read') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('teacher', 'content:question:write') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('teacher', 'content:node:write') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('teacher', 'content:ladder:write') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('teacher', 'content:review:approve') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('teacher', 'learn:session:read_scope') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('teacher', 'learn:mastery:read_scope') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('teacher', 'learn:attempt:read_scope') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('teacher', 'config:class:update') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('teacher', 'config:student:update') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('teacher', 'assess:summative:grade') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('teacher', 'intervene:manage') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('teacher', 'live:classroom:run') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('teacher', 'report:student:read') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('teacher', 'report:class:read') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('teacher', 'safety:flag:read') on conflict do nothing;
delete from public.role_permissions where role_key = 'homeroom_teacher';
insert into public.role_permissions (role_key, perm_key) values ('homeroom_teacher', 'learn:session:read_scope') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('homeroom_teacher', 'learn:mastery:read_scope') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('homeroom_teacher', 'learn:attempt:read_scope') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('homeroom_teacher', 'intervene:manage') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('homeroom_teacher', 'report:student:read') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('homeroom_teacher', 'report:class:read') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('homeroom_teacher', 'safety:flag:read') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('homeroom_teacher', 'config:student:update') on conflict do nothing;
delete from public.role_permissions where role_key = 'subject_lead';
insert into public.role_permissions (role_key, perm_key) values ('subject_lead', 'content:kg:read') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('subject_lead', 'content:question:read') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('subject_lead', 'content:question:write') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('subject_lead', 'content:node:write') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('subject_lead', 'content:ladder:write') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('subject_lead', 'content:review:approve') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('subject_lead', 'content:question:retire') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('subject_lead', 'config:subject:update') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('subject_lead', 'learn:mastery:read_scope') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('subject_lead', 'report:class:read') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('subject_lead', 'ai:prompt:manage') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('subject_lead', 'ai:budget:read') on conflict do nothing;
delete from public.role_permissions where role_key = 'counselor';
insert into public.role_permissions (role_key, perm_key) values ('counselor', 'safety:flag:read') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('counselor', 'safety:flag:verify') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('counselor', 'safety:flag:resolve') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('counselor', 'wellbeing:context:read') on conflict do nothing;
delete from public.role_permissions where role_key = 'content_author';
insert into public.role_permissions (role_key, perm_key) values ('content_author', 'content:kg:read') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('content_author', 'content:node:write') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('content_author', 'content:question:write') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('content_author', 'content:ladder:write') on conflict do nothing;
delete from public.role_permissions where role_key = 'content_reviewer';
insert into public.role_permissions (role_key, perm_key) values ('content_reviewer', 'content:kg:read') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('content_reviewer', 'content:question:read') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('content_reviewer', 'content:review:approve') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('content_reviewer', 'content:question:retire') on conflict do nothing;
delete from public.role_permissions where role_key = 'campus_admin';
insert into public.role_permissions (role_key, perm_key) values ('campus_admin', 'org:campus:manage') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('campus_admin', 'org:class:manage') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('campus_admin', 'iam:user:manage') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('campus_admin', 'config:tenant:update') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('campus_admin', 'report:school:read') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('campus_admin', 'audit:log:read') on conflict do nothing;
delete from public.role_permissions where role_key = 'leadership';
insert into public.role_permissions (role_key, perm_key) values ('leadership', 'report:school:read') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('leadership', 'report:class:read') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('leadership', 'ai:budget:read') on conflict do nothing;
delete from public.role_permissions where role_key = 'dpo';
insert into public.role_permissions (role_key, perm_key) values ('dpo', 'privacy:consent:read') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('dpo', 'privacy:dsar:fulfill') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('dpo', 'privacy:dpia:manage') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('dpo', 'audit:log:read') on conflict do nothing;
delete from public.role_permissions where role_key = 'admin';
insert into public.role_permissions (role_key, perm_key) values ('admin', 'org:tenant:read') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('admin', 'org:tenant:configure') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('admin', 'org:campus:manage') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('admin', 'org:class:manage') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('admin', 'iam:user:manage') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('admin', 'iam:role:grant') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('admin', 'iam:permission:simulate') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('admin', 'privacy:consent:read') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('admin', 'privacy:consent:grant') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('admin', 'privacy:consent:withdraw') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('admin', 'privacy:dsar:fulfill') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('admin', 'privacy:dpia:manage') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('admin', 'content:kg:read') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('admin', 'content:node:write') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('admin', 'content:question:read') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('admin', 'content:question:write') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('admin', 'content:ladder:write') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('admin', 'content:review:approve') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('admin', 'content:question:retire') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('admin', 'learn:tutor:chat') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('admin', 'learn:session:read_own') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('admin', 'learn:session:read_scope') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('admin', 'learn:mastery:read_own') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('admin', 'learn:mastery:read_scope') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('admin', 'learn:attempt:read_scope') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('admin', 'config:tenant:update') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('admin', 'config:subject:update') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('admin', 'config:class:update') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('admin', 'config:student:update') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('admin', 'config:feature_flag:update') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('admin', 'assess:summative:grade') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('admin', 'intervene:manage') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('admin', 'live:classroom:run') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('admin', 'report:student:read') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('admin', 'report:class:read') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('admin', 'report:school:read') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('admin', 'report:parent:read') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('admin', 'safety:flag:read') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('admin', 'safety:flag:verify') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('admin', 'safety:flag:resolve') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('admin', 'wellbeing:context:read') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('admin', 'ai:prompt:manage') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('admin', 'ai:model:configure') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('admin', 'ai:budget:read') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('admin', 'ai:eval:run') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('admin', 'audit:log:read') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('admin', 'ops:manage') on conflict do nothing;
insert into public.role_permissions (role_key, perm_key) values ('admin', 'saas:manage') on conflict do nothing;
